name: Build

on: push

env:
  BUILD_TYPE: Release
  
jobs:
  windows:
    runs-on: windows-latest
    name: Windows
    defaults:
      run:
        shell: msys2 {0}
  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          autoconf
          automake
          git
          make
        pacboy: >-
          toolchain:p
          qt5-base:p
          cmake:p
        
        
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        ninja
        dir /s /b
        
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: result
          path:  D:/a/_temp/maze-solver-robot/build/
        
    
